### ISSUE TITLE
encoding alpha bet is not 64-bytes long

### ISSUE THREAD

**Issue by yangmu266** [GiterLab/goots#3]
the length of encoding alpha bet should be 64 in go version 1.5
but in function base64Encoding/base64Decode(protocol.go, line 460), the length of coder is 65
btw, why not use base64.StdEncoding?

**Comment by tobyzxj** [comment]
@yangmu266, thanks for your feedback. `base64Encoding/base64Decode` is porting form my C code, the `=` indicates that is the padding. `base64.NewEncoding(encoder string)` in [go1.5](https://github.com/golang/go/blob/master/src/encoding/base64/base64.go#L40-#L56) will check the length of encoder alphabet, but not in [go1.4](https://github.com/golang/go/blob/release-branch.go1.4/src/encoding/base64/base64.go#L34-#L44). I will fix it.
