### ISSUE TITLE
Client goroutine leak

### ISSUE THREAD

**Issue by hryang** [GiterLab/goots#6]
您好，感谢开发ots golang sdk。我们在项目中使用这个sdk，但是client无法通过goroutine leak的check。client没有类似Close这样的清理函数，请问是怎么释放http链接等资源的？

这里是goroutine leak的信息：
<img width="541" alt="dingtalk20170217151049" src="https://cloud.githubusercontent.com/assets/626967/23055886/4c9658b4-f523-11e6-9448-3fc917511e04.png">

**Comment by liudanking** [comment]
是仅仅无法通过测试还是在生产环境中遇到了leak的问题？

**Comment by hryang** [comment]
我们还没用于生产。有办法能释放client的资源吗？

**Comment by liudanking** [comment]
应该是不断创建http client导致。你把DiableKeepallive设置为true应该可行

**Comment by tobyzxj** [comment]
@hryang ots本身是使用http请求进行通信的，http调用时client自己设置了60秒的超时（默认值），如果client调用失败会自动关闭的，无需再手动关闭。

这个ots golang sdk，当时ots没有golang版本的sdk，我们才自己写了一个。我们线上已经跑了1年多了，其中也发现的一些bug也得到了修复。到现在没出现过其他异常。

另外和阿里团队沟通过，他们也正在开发一个golang的sdk，https://github.com/aliyun/aliyun-tablestore-go-sdk, 请参考

**Comment by tobyzxj** [comment]
@liudanking 这里有个误区，如果你把DiableKeepallive设置为true的话，那么每次http请求都是重新创建新的TCP连接，当让之前的tcp连接会被关闭。但是这样的话，如果你请求很多数据到ots，那么会频繁的创建和关闭TCP连接，你请求到ots服务的数据速度会很慢(创建和关闭tcp是很消耗时间的，3次握手，4次断开)。

其实golang底层本身就给我们维护好了一个http(tcp)的连接池，你只要不主动关闭http连接，底层的tcp连接是一直在的，就算你应用程序不停的创建新的`REQUSET`，底层也是使用同一个tcp通道进行数据交互。如果你觉得底层一个tcp连接不够，那么你可以多创建几个ots的client。

如果描述错误，请指正。

**Comment by tobyzxj** [comment]
已增加设置tcp连接池功能。
